Contact us
Miskamyasa/SetupIsrael pull request #7
Opened 2023-09-02 14:29 UTC by YevBor

2023-09-02 14:31 UTC, Miskamyasa commented on src/components/input/Input.astro
> +  label?: string
если лейбл может быть андефайнд, надо тогда его проверять на наличие в разметке
`{label ? JSX : null}

2023-09-02 14:32 UTC, Miskamyasa requested changes

2023-09-02 14:32 UTC, Miskamyasa commented on src/components/input/Input.astro
> +<label
`{label ? JSX : null}`

2023-09-02 14:32 UTC, Miskamyasa commented on src/pages/index.astro
> +changeLanguage("en");
error

2023-09-09 08:18 UTC, YevBor commented on src/components/input/Input.astro
> +<label
ya sdelal prosto 
{label && JSX}

2023-09-09 08:49 UTC, Miskamyasa approved these changes

2023-09-09 08:49 UTC, merged